# Generated by Django 6.1 on 2026-08-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_audio_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'réaction', 'verbose_name_plural': 'réactions'},
        ),
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', "J'aime"), ('love', 'Adore'), ('celebrate', 'Féliciter'), ('funny', 'Réjouir'), ('insightful', 'Inspirant'), ('support', 'Soutenir')], default='like', max_length=12, verbose_name='Réaction'),
        ),
    ]
