# Generated by Django 6.1 on 2026-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_onlinestatus_poll_polloption_report_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, upload_to='stories/video/%Y/%m/%d/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('text', 'Texte'), ('audio', 'Audio')], default='image', max_length=6),
        ),
    ]
