# Generated by Django 6.1 on 2026-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO 639-3 (ex. fon, yor)', max_length=8, unique=True, verbose_name='Code ISO')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_native', models.CharField(blank=True, max_length=100, verbose_name='Nom d’origine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ui_available', models.BooleanField(default=False, help_text="Vrai si l'interface du site existe dans cette langue.", verbose_name='Interface traduite')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['name'],
            },
        ),
    ]
