# Generated by Django 6.1 on 2026-08-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Langues béninoises que tu parles (Fon, Yoruba, Adja…).', related_name='speakers', to='core.language', verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ui_language',
            field=models.ForeignKey(blank=True, help_text='Langue utilisée pour afficher le site (vide = français).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.language', verbose_name='Langue de l’interface'),
        ),
    ]
